language: ruby
rvm:
  - 2.0.0  # replace this with the ruby version you are using in development
rake:
  - 10.4.2
before_script:
  - psql -c 'create database audit_work_flow_test;' -U postgres
  - bundle exec rake db:migrate
  - rake db:seed
